name: PlatformIO CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Build PlatformIO Project
      run: pio run
    - name: Upload firmware as artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          .pio/build/*/firmware.bin
          .pio/build/*/firmware.elf
          .pio/build/*/*.hex
        if-no-files-found: warn