name: PlatformIO Build and Release

on:
  push:
    branches: [ release ]  # Only run on the release branch
    tags:
      - 'v*'  # Run workflow on version tags, e.g. v1.0.0
  pull_request:
    branches: [ release ]  # Only run on PRs to the release branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Build PlatformIO Project
      run: pio run
    - name: Upload firmware as workflow artifact
      uses: actions/upload-artifact@v4 
      with:
        name: firmware
        path: |
          .pio/build/*/firmware.bin
          .pio/build/*/*.bin
          .pio/build/*/firmware.elf
          .pio/build/*/*.hex
        if-no-files-found: warn
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          .pio/build/*/firmware.bin
        draft: false
        prerelease: false
        generate_release_notes: true